### ISSUE TITLE
If we set multiple audience, we get the authentication error.

### ISSUE THREAD

**Issue by shnmorimoto** [auth0/go-jwt-middleware#148]
### Describe the problem

When we set multiple audience and jwt only have one audience. then we got authentication error.

```go
jwtValidator, err := validator.New(
	provider.KeyFunc,
	validator.RS256,
	issuerURL.String(),
	[]string{"aaaaaa", "bbbbbb"},
)
```

jwt payload is like below
```JSON
{
  "email": "user@example.com",
  "email_verified": true,
  "iss": "xxxxxxxxxxxxxxxx",
  "sub": "xxxxxxxxxxxxxxxx",
  "aud": "aaaaaa",
  "iat": 1648000756,
  "exp": 1648036756
}
```

error is like below.
```
2022/03/23 08:08:42 Encountered error while validating JWT: jwt invalid: expected claims not validated: square/go-jose/jwt: validation failed, invalid audience claim (aud)
```

if we set only 1 audience. then we get success authentication

### What was the expected behavior?

In my understanding, 
if one of the audiences we set matches one of the client-side audiences, the authentication should succeed.

My understanding is correct?

### Reproduction

1. set multiple audience in validator.New.
2. send jwt with one audience

please see `Describe the problem`

### Environment

Version of `go-jwt-middleware` used: v2.0.1

**Comment by sergiught** [comment]
Hey folks 👋🏻 this is now fixed within the [v2.1.0 (release)](https://github.com/auth0/go-jwt-middleware/releases/tag/v2.1.0). Thanks for your patience!
