### ISSUE TITLE
Pass the unverified token to Validator keyFunc

### ISSUE THREAD

**Issue by danpoland** [auth0/go-jwt-middleware#149]
### Describe the problem you'd like to have solved

In the v1 version of this library the `ValidationKeyGetter` attribute of the `Options` struct is passed a pointer to the unverified jwt `Token` object.  In v2 `ValidationKeyGetter` has been replaced with `validator.New`'s first argument which is of type `func(context.Context) (interface{}, error)`.

The unverified token is no longer provided to the function used to retrieve the validation key. V1 allowed you to use properties in the header of the token (such as `kid`) to identify which key to use. V2 doesn't seem to support this.

### Describe the ideal solution

Provide the unverified token to to the `Validator.keyFunc` function.

**Comment by danpoland** [comment]
I figured out what I needed by going through the source code.

**Comment by JeremyCraven** [comment]
Hey @danpoland what was the solution here?

**Comment by danpoland** [comment]
@JeremyCraven there are some features that aren't documented in the github README. I was looking for a way to implement JWKS caching, as it turns out the library already provided the functionality, https://pkg.go.dev/github.com/auth0/go-jwt-middleware/v2/jwks.

You can find an example of its usage here: https://auth0.com/docs/quickstart/backend/golang/01-authorization
