### ISSUE TITLE
Failed to get decoded token using Go fiber

### ISSUE THREAD

**Issue by kacak9229** [auth0/go-jwt-middleware#166]
**Please do not report security vulnerabilities here**.
The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!**
Your attention to detail here is greatly appreciated and will help us respond as quickly as possible.
For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or
[Auth0 Support](https://support.auth0.com/).
Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the
[Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I'm using gofiber https://gofiber.io/ and so far I managed to validate the token. I followed this [tutorial](https://auth0.com/docs/quickstart/backend/golang/01-authorization)

I had to convert using the middleware using this library - https://github.com/gofiber/adaptor

Example code:
   
   ```
 func main() {
	 app := fiber.New()
	 app.Use(cors.New())
	
	 app.Use(adaptor.HTTPMiddleware(EnsureValidToken())
	 app.Get("/api/books", books.GetAll)
     }
```

and based on the code I know that it will store in the Context

`r = r.Clone(context.WithValue(r.Context(), ContextKey{}, validToken))`

Route example:

 ```
   func GetAll(c *fiber.Ctx) error {
        token := c.Context().Value(jwtmiddleware.ContextKey{}).(*validator.ValidatedClaims)

         // The above code will always panic, I'm assuming that it already stored in the context since it passes the validation
    }

```

Panic example

   **_panic: interface conversion: interface {} is nil, not *validator.ValidatedClaims_**

Any help will be really useful. Thanks

**Comment by sergiught** [comment]
Hey @kacak9229 👋🏻 

Apologies for the late reply, I took a look at this and it seems to be an issue with the fiber adaptor pkg. The `HTTPMiddleware` func doesn't seem to be copying over the original request Context. 

If you add `c.SetUserContext(r.Context())` within the `nextHandler` of the `adaptor.HTTPMiddleware()` and then within your handler do `claims, ok := ctx.UserContext().Value(jwtmiddleware.ContextKey{}).(*validator.ValidatedClaims)` you'll see that we're now getting the context value with the claims. 

This is unfortunately not a bug with this SDK but rather with the usage of the 3rd party (fiber), as such we'll be closing this down.
