### ISSUE TITLE
CheckJWT with Martini throwing <invalid Value>?

### ISSUE THREAD

**Issue by natdm** [auth0/go-jwt-middleware#17]
I'm trying the JWT middleware examples to get JWT to work with Martini and it's giving me an return when it hits the authentication handler.

Here's the code, straight from the examples..

```
package main

import (
    "encoding/json"
    "github.com/auth0/go-jwt-middleware"
    "github.com/dgrijalva/jwt-go"
    "github.com/go-martini/martini"
    "net/http"
)

func main() {

    StartServer()

}

func StartServer() {
    m := martini.Classic()

    jwtMiddleware := jwtmiddleware.New(jwtmiddleware.Options{
        ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {
            return []byte("My Secret"), nil
        },
        SigningMethod: jwt.SigningMethodHS256,
    })

    m.Get("/ping", PingHandler)
    m.Get("/secured/ping", jwtMiddleware.CheckJWT, SecuredPingHandler)

    m.Run()
}

type Response struct {
    Text string `json:"text"`
}

func respondJson(text string, w http.ResponseWriter) {
    response := Response{text}

    jsonResponse, err := json.Marshal(response)
    if err != nil {
        http.Error(w, err.Error(), http.StatusInternalServerError)
        return
    }

    w.Header().Set("Content-Type", "application/json")
    w.Write(jsonResponse)
}

func PingHandler(w http.ResponseWriter, r *http.Request) {
    respondJson("All good. You don't need to be authenticated to call this", w)
}

func SecuredPingHandler(w http.ResponseWriter, r *http.Request) {
    respondJson("All good. You only get this message if you're authenticated", w)
}
```

If I hit the unauthenticated route, it works. If I hit the authenticated route, it tells me I need a token. If I hit the authenticated route with a token that's not right, I get an error stating,

```
signature is invalid
<*errors.errorString Value>
```

So all that works. If I hit the authenticated route with the right token, it gives me as the return text. I can't find out why. This is straight from their example, though I get the same in my personal project.

**Comment by grounded042** [comment]
Is this still a problem? I'm going through and cleaning some things up, so if I don't hear back after a couple of days I'll close this issue.

**Comment by grounded042** [comment]
I'm closing this issue due to no response. If this is still a problem please feel free to re-open this issue.

**Comment by barismar** [comment]
I've solved this issue on this PR [https://github.com/auth0/go-jwt-middleware/pull/78](url), please kindly check it.
