### ISSUE TITLE
Custom `ValidateWithLeeway` in  #176 Introduced Breaking Changes to Token Validation

### ISSUE THREAD

**Issue by josh-feldman** [auth0/go-jwt-middleware#178]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-jwt-middleware#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-jwt-middleware/v2) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-jwt-middleware/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-jwt-middleware/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In #176 with the introduction of the custom `validateClaimsWithLeeway` function, [the audience validation](https://github.com/auth0/go-jwt-middleware/blob/b895d8b2e2af97a43fa7616a1132b0185c435f5c/validator/validator.go#L145-L154) the package dropped support for an empty `expectedClaims.Audience`.

Previously `*jwt.validateClaimsWithLeeway` would be called when validating a token, which ignored expectations that were left empty & allowed the caller to decide what they would like to validate. For example, [this snippet of code from their audience validation](https://github.com/square/go-jose/blob/a10ff54e00bc6e833bf549e04ae976f0fe8ea2fd/jwt/validation.go#L89-L95) ignores the audience if the expected audiences is empty.

## Expected Behavior
When validating a token with a validator that had an empty audience slice, the validator should ignore the audience claim.

## Actual Behavior
A validator with an empty expected Audience slice will always fail any token on validation. This could be mitigated by wrapping in an `if len(expectedClaims.Audience) > 0` or initializing `foundAudience` to true if there are no expected audiences. 

### Reproduction

1. Given you call the validator with an empty expected audience slice
2. The token will always fail validation as `foundAudience` defaults to false

### Go JWT Middleware version

v2.1.0

### Go version

v1.19

**Comment by sergiught** [comment]
Hey @josh-feldman 👋🏻 

Thanks for raising this and apologies for the unexpected behavior change. The fact that the previous version allowed passing an empty audience slice and skipping the validation, was flawed and was considered a bug. Validation should always occur on the issuer, audience and time based claims.

**Comment by josh-feldman** [comment]
@sergiught should we at least change the error to validate an empty audience array as `invalid expectations` or `at least one audience must be specified`? The current error for not passing in an audience array and getting back that the token is invalid regardless of whether the audience field exists or not is misleading.

**Comment by sergiught** [comment]
Agreed @josh-feldman, the error message definitely needs to be improved and fire earlier when we set up the validator in case the audience is nil or len 0.
