### ISSUE TITLE
context.Set() but no context.delete()

### ISSUE THREAD

**Issue by pkartner** [auth0/go-jwt-middleware#18]
Is there a special reason you call context.Set(r, m.Options.UserProperty, parsedToken) without calling the delete for that entry? This seems like a memory leak to me but I didn't get the chance to test it yet.

**Comment by kohenkatz** [comment]
Note that as of 91fde50a187e033f6d474b855ff41bdb4dab0ff7 this is no longer how `context` is used, and the new way does not have this issue because the `Request` object is cleaned up after the request is over.

**Comment by grounded042** [comment]
I'm going through and cleaning up issues - it looks like this one is no longer needed. Feel free to open it again if it is needed.
