### ISSUE TITLE
Cannot import internal oidc package

### ISSUE THREAD

**Issue by harshav17** [auth0/go-jwt-middleware#182]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-jwt-middleware#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-jwt-middleware/v2) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-jwt-middleware/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-jwt-middleware/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

While following the example described in the repo: https://github.com/auth0/go-jwt-middleware/tree/master/examples/http-jwks-example. Initializing the test file fails with the error...

`
could not import github.com/auth0/go-jwt-middleware/v2/internal/oidc (invalid use of internal package github.com/auth0/go-jwt-middleware/v2/internal/oidc)
`

### Reproduction

1. Copied main.go and main_test.go.
2. Tried to get oidc package.

**Expected:** Import is successful.
**Actual:** Import fails with...

`
could not import github.com/auth0/go-jwt-middleware/v2/internal/oidc (invalid use of internal package github.com/auth0/go-jwt-middleware/v2/internal/oidc)
`

### Go JWT Middleware version

2.1.0

### Go version

1.18

**Comment by sergiught** [comment]
Thanks for reporting this @harshav17 ! The internal pkg was included by mistake in the examples, however they are now fixed! Please have a look at the updated ones: https://github.com/auth0/go-jwt-middleware/blob/master/examples/http-jwks-example/main_test.go. Appreciate your patience!
