### ISSUE TITLE
Improve performance of JWKS Caching Provider

### ISSUE THREAD

**Issue by pdewilde** [auth0/go-jwt-middleware#194]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently jwks/CachingProvider uses a global lock within its key function: https://github.com/auth0/go-jwt-middleware/blob/c83a8240478c645000da517a56f31da40bf16802/jwks/provider.go#L129

This is in the hot path of every call to validate:
https://github.com/auth0/go-jwt-middleware/blob/c83a8240478c645000da517a56f31da40bf16802/validator/validator.go#L183

This effectively serializes every http call that the middelware handles, and adds a good deal of locking overhead.

Additionally, there is no "refresh before expiry" mechanism, which mean you are guaranteed to block when the key expires after TTL minutes.

### Describe the ideal solution

To avoid a global lock, you could use a `sync.RWMutex`, which makes sense in the JWKS  usecase where most calls to the cache will be readers. This allows multiple readers to concurrently access the critical path, and only blocks when a writer needs to update a key.

An example implementation can be found: https://github.com/sethvargo/go-cache/blob/main/ttl.go

To avoid the blocking problem, you can use a reloading chache. I'm not too familiar with the options in the go ecosystem, but in Java there is both [caffine](https://github.com/ben-manes/caffeine/wiki/Refresh) and [Guava](https://github.com/google/guava/wiki/CachesExplained). The main idea is to reload keys asynchronously before they expire, so that you don't have to wait to refresh a hot key. 

The semantics for such a cache are that a key is "stale" after some time, and stale reads return with the cached value immediately but asynchronously kick off a fetch (with additional checks that a fetch for the key isn't currently in progress). If a key does get old enough that expires, you then will have a blocking fetch.

**Comment by pdewilde** [comment]
It appears that https://github.com/s12v/go-jwks may implement refreshing before expirary

**Comment by pdewilde** [comment]
Another example here: https://pkg.go.dev/github.com/lestrrat-go/jwx/v2/jwk#section-readme

**Comment by ewanharris** [comment]
We worked on improving this in #225 and it's now released as v2.2.0.

Thanks again for this issue @pdewilde!
