### ISSUE TITLE
Has jwt-go changed since the README was published?

### ISSUE THREAD

**Issue by seanlindo** [auth0/go-jwt-middleware#20]
This code snippet no longer works:

`for k, v := range user.(*jwt.Token).Claims {
    fmt.Fprintf(w, "%s :\t%#v\n", k, v)
  }`

`Claims` cannot be ranged over, but I assume this was possible previously. I'm actually unsure how to access any of the claims at all from inside of the handler. When I log `Claims`, it's logged as a map. When I try to work with `Claims` as one would work with a map, I just get a litany of errors.

**Comment by seanlindo** [comment]
Ah, `Claims` has changed in the latest release. I'm going to issue a PR to update the example.

**Comment by rushstrike** [comment]
I ran into this problem today. This is what I changed to get it to work:
	for k, v := range user.(*jwt.Token).Claims.(jwt.MapClaims) {
		fmt.Fprintf(w, "%s :\t%#v\n", k, v)
	}

**Comment by grounded042** [comment]
It looks like we've got a solid solution from @TaiPhamD above. Since then we've gotten modules and in our future `v2` release we will be able to utilize them to keep things from breaking like they did here.
