### ISSUE TITLE
go-jose v2 is deprecated, should be upgraded to v3

### ISSUE THREAD

**Issue by ewintr** [auth0/go-jwt-middleware#239]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-jwt-middleware#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-jwt-middleware/v2) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-jwt-middleware/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-jwt-middleware/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Development of the go-jose module apparently has moved to a new organization, according to the README: https://github.com/square/go-jose

The v2 that is currently used is deprecated, v3 is in the new repository. It's probably best to update the dependencies to use this new version.

### Reproduction

1. Open go.mod
2. See a line that says `gopkg.in/go-jose/go-jose.v2 v2.6.2`

### Go JWT Middleware version

v2.2.0

### Go version

any

**Comment by adam2k** [comment]
@ewintr it looks like https://github.com/go-jose/go-jose/releases/tag/v2.6.2 was released last month.  Since v3 would be a breaking change it might not be urgent to change since v2 is still being maintained.  Where did you see that v2 is being sunset or deprecated?

**Comment by ewintr** [comment]
Oops, my mistake. The repository I linked to was deprecated, but not the version. And I see you already migrated to the new repository. So there is no problem. I'll close the issue.
