### ISSUE TITLE
Support for Gin

### ISSUE THREAD

**Issue by Dev-Destructor** [auth0/go-jwt-middleware#243]
### Checklist

- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am having trouble configuring the package with my gin-based server. I am not sure why the package is not framework-independent. Will there be support for gin in the future? 

### Describe the ideal solution

The problem is self-explanatory.

**Comment by ewanharris** [comment]
Hey @Dev-Destructor, we provide an example of how to integrate with Gin [here](https://github.com/auth0/go-jwt-middleware/tree/master/examples/gin-example). Does that help with your query?

**Comment by ewanharris** [comment]
Closing as I believe this should be answered by the Gin example

**Comment by mftcodes** [comment]
@ewanharris Can you provide a little guidance on how to use the Auth0 secret effectively? I've tried many ways and I cannot get the example GIN code to work with my tenant.
