### ISSUE TITLE
Can't verify signature

### ISSUE THREAD

**Issue by andrew-jones** [auth0/go-jwt-middleware#25]
I have am using the Angular2 project from here, https://github.com/auth0/auth0-angular2

I've created a go service built using gin and have created a middleware to decode and verify the JWT passed from the Angular2 app to the go service.  I can verify the JWT sent in the Auth header from angular to the go service using jwt.io and my auth0 client secret.  However using this middleware I can't seem to verify the signature.  Am I missing something fundamental?

    func jwtMiddleware() gin.HandlerFunc {
    	return func(c *gin.Context) {
            str := "Secret copied from Auth0 dashboard"

            // Testing base64 decode, also tried returning base64Text as []byte(base64Text) in ValidationKeyGetter
            base64Text := make([]byte, base64.StdEncoding.DecodedLen(len(str)))
            base64.StdEncoding.Decode(base64Text, []byte(str))
            fmt.Printf("base64: %s\n", base64Text)

            jwtMiddleware := jwtmiddleware.New(jwtmiddleware.Options{
                ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {
                    return []byte(str), nil
                },
                SigningMethod: jwt.SigningMethodHS256,
            })

            err := jwtMiddleware.CheckJWT(c.Writer, c.Request)

            if err != nil {
                c.AbortWithStatus(401)
            } else {
                c.Next()
            }
    	}
    }

The response is always, 'signature is invalid'

**Comment by andrew-jones** [comment]
Solved with

    base64.URLEncoding.DecodeString(str)

**Comment by ritik2409** [comment]
Great Work, Dude!!!
