### ISSUE TITLE
Context may be too specific?

### ISSUE THREAD

**Issue by yageek** [auth0/go-jwt-middleware#27]
In the current implementation, we have a dependencies on `gorilla/context`. Some framework do not use this package. It may make sense to remove the dependency to it no ?

**Comment by cam-stitt** [comment]
I have an open PR that helps fix this: #19

**Comment by yageek** [comment]
See my updated comment in the PR #19

**Comment by grounded042** [comment]
Please see https://github.com/auth0/go-jwt-middleware/pull/19#issuecomment-516598326
