### ISSUE TITLE
Gin middleware

### ISSUE THREAD

**Issue by zlepper** [auth0/go-jwt-middleware#28]
I would very much like to see some middleware for this that works with the [gin](https://github.com/gin-gonic/gin) framework.

**Comment by dstroot** [comment]
+1

**Comment by Err0r500** [comment]
Hey,
I just wrote an example : https://gist.github.com/Err0r500/00c50d45a5337058c4c732206457bd64
hope this helps,

**Comment by dstroot** [comment]
This is very helpful - very easy to get running.  ;)

Now for the hard part - I cannot figure out how to actually use Auth0 to issue a JWT token that I can use to try the authenticated route.

**Comment by alexbrand** [comment]
@dstroot Were you able to generate some kind of test JTW for testing? Thanks

**Comment by dstroot** [comment]
Actually never was able to figure it out.  I ended up using a different JWT library.

**Comment by grounded042** [comment]
I'm going through and cleaning some old issue up - it looks like this issue is no longer active so I'll close it for now. Feel free to open it again if this is still an issue.
