### ISSUE TITLE
gorilla/context is not compatible with Go 1.7

### ISSUE THREAD

**Issue by ricochet2200** [auth0/go-jwt-middleware#29]
https://github.com/gorilla/context

> Note: gorilla/context, having been born well before context.Context existed, does not play well with the shallow copying of the request that http.Request.WithContext (added to net/http Go 1.7 onwards) performs. You should either use just gorilla/context, or moving forward, the new http.Request.Context().

It seems this project should no longer use gorilla context, but should replace it with the new package Go provides.  Perhaps [build constraints](https://golang.org/pkg/go/build/) (see Build Constraints section) could allow supporting both versions depending on what version of go is being used.

It also appears, a "go1.6" tag on this current version would cause `go get` to checkout that tag for users that have go 1.6 installed.  From [go cmd docs](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies):

> When checking out or updating a package, get looks for a branch or tag that matches the locally installed version of Go. The most important rule is that if the local installation is running version "go1", get searches for a branch or tag named "go1". If no such version exists it retrieves the most recent version of the package.

There is already a fork of this project that [removes gorilla context](https://github.com/aiden0z/go-jwt-middleware/commits/master).  If the current state were tagged, the branch could be merged in.

**Comment by socceroos** [comment]
and for those still using Gorilla Context with the current master, just rename the import to ctx and then update the use of the package on line 232 of jwtmiddleware.go.

**Comment by grounded042** [comment]
We are now using the go context here. I'm going through and cleaning some old issue up - it looks like this issue is no longer active so I'll close it for now. Feel free to open it again if this is still an issue.
