### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by theobouwman** [auth0/go-jwt-middleware#39]
```
jwtMiddleware := jwtmiddleware.New(jwtmiddleware.Options{
		ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {
			return []byte("My Secret"), nil
		},
		SigningMethod: jwt.SigningMethodHS256,
})
```

This throws the error:
```
cannot use func literal (type func(*"bitbucket.org/woodyzapp/woodyplatform/vendor/github.com/dgrijalva/jwt-go".Token) (interface {}, error)) as type "github.com/dgrijalva/jwt-go".Keyfunc in field value
```

I am using Govendor

**Comment by theobouwman** [comment]
The problem occurred because it was searching for the package in my `GOPATH` but since I am using `govendor` it was using the wrong package.

**Comment by claudioontheweb** [comment]
> The problem occurred because it was searching for the package in my `GOPATH` but since I am using `govendor` it was using the wrong package.

Could you please tell how exactly you fixed that? It seems like I have the same problem. Thank you!
