### ISSUE TITLE
Is this library vendor neutral?

### ISSUE THREAD

**Issue by etsangsplk** [auth0/go-jwt-middleware#40]
It is not clear in README that this library vendor neutral. 
It looks like it is. Please clarify and to what extent it implement the spec

**Comment by grounded042** [comment]
Hey @etsangsplk! I realize that this comment is very late in regards to when you created this issue and I'm sorry about that. We are ramping up work on a version 2 of this package and we wanted to consider this issue as we plan. 

Could you clarify a bit what you mean by vendor neutral? Are you talking about if this package just works with Auth0 or if it works with other auth providers? Or are you asking about the ability to use different packages to handle the core JWT validation logic? Or maybe you're asking something totally different.

**Comment by sergiughf** [comment]
We just released the [v2.0.0-beta](https://github.com/auth0/go-jwt-middleware/releases/tag/v2.0.0-beta) 🥳 ! 

You can start testing it by running `go get github.com/auth0/go-jwt-middleware/v2@v2.0.0-beta`. 

In case of issues fetching the v2 you might want to try `go clean --modcache` first before doing `go get`.

I'm closing this issue as now this is part of v2, but feel free to reopen if needed.
