### ISSUE TITLE
Negroni example

### ISSUE THREAD

**Issue by sergot** [auth0/go-jwt-middleware#49]
Hey

It looks to me, like when we use negroni, we have to write explicitly that we want to use the middleware, everytime we use it. Am I wrong?

What to do when, for example, I have 25 secured routes, and 2 not secured (they don't need user to send the token), do I have to write this:

        r.Handle("/ping", negroni.New(
            negroni.HandlerFunc(jwtMiddleware.HandlerWithNext),
            negroni.Wrap(myHandler),
        ))

25 times?

Can I somehow use negroni.Use() ?

Best Regards :)

**Comment by stephanebruckert** [comment]
+1 anyone got a solution for this?

**Comment by grounded042** [comment]
Is this still a problem? I'm going through and cleaning some things up, so if I don't hear back after a couple of days I'll close this issue.

**Comment by stephanebruckert** [comment]
@grounded042 I still wonder if there is a solution to avoid duplicating the middleware bit

**Comment by grounded042** [comment]
@stephanebruckert depending on the route setup I believe you could do something like this
```
router := mux.NewRouter()
routesNeedingAuth := mux.NewRouter()

router.PathPrefix("/routes-needing-auth").Handler(negroni.New(
  negroni.HandlerFunc(jwtMiddleware.HandlerWithNext),
  negroni.Wrap(<routes needing auth>),
))
```

**Comment by grounded042** [comment]
@stephanebruckert does that solve the issue for you?

**Comment by stephanebruckert** [comment]
Can't try it now but feel free to close as that looks like a good answer to me! Thanks for the help
