### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by xogeny** [auth0/go-jwt-middleware#5]
This library really needs some tests.  I would propose that one goal should be to add some.

Personally, I really like using `goconvey` for my testing.  It works perfectly fine with the normal `go test` command line.  But it also includes a nice web interface that continuously reruns tests.

Any objections to adding some tests using `goconvey`?

**Comment by mgonto** [comment]
No objection at all. I think it's an awesome idae.

**Comment by javiercbk** [comment]
I've just made a quick test case using negroni and go convey. It could use some refactor but it's a start

**Comment by mgonto** [comment]
Thanks for the help on this. Merged!
