### ISSUE TITLE
Support for custom Claims

### ISSUE THREAD

**Issue by Mathiou04** [auth0/go-jwt-middleware#53]
Are there any plans to support custom Claims as the underlying library _jwt-go_ does (with the `parseWithClaims` method) ?

If no, is there any reason for not adding it to the library? (I am willing to open a PR if anyone has an idea on what is the best way to add support for this)

**Comment by hleonps** [comment]
Any update about it?

**Comment by giautm** [comment]
I think this project was not maintained anymore. so, we should fork to add new feature & fix bugs

**Comment by ciehanski** [comment]
I have forked this project and got the tests to run. Also applied most open PRs and issues. https://github.com/ciehanski/go-jwt-middleware

**Comment by giautm** [comment]
I switched to use this package, `github.com/dgrijalva/jwt-go`

**Comment by grounded042** [comment]
I apologize for the inactivity here. We are beginning work on a `v2` and this is something we can look at. Note that the package we settle on to replace `jwt-go` might impact how custom claims are supported. See #73 for more details on the replacement of `jwt-go`.

**Comment by sergiughf** [comment]
We just released the [v2.0.0-beta](https://github.com/auth0/go-jwt-middleware/releases/tag/v2.0.0-beta) 🥳 ! 

You can start testing it by running `go get github.com/auth0/go-jwt-middleware/v2@v2.0.0-beta`. 

In case of issues fetching the v2 you might want to try `go clean --modcache` first before doing `go get`.

I'm closing this issue as now this is part of v2, but feel free to reopen if needed.
