### ISSUE TITLE
Why you are not extracting token from session cookie?

### ISSUE THREAD

**Issue by AleksandrukTad** [auth0/go-jwt-middleware#63]
Hey, 
When you are implementing this login: https://auth0.com/docs/quickstart/webapp/golang/01-login

You are not able to implement this authorization:
https://auth0.com/docs/quickstart/backend/golang/01-authorization

Because the access_token is store in session cookie which Extractor is not handling. If you want me to I can have a look, and implement this.

**Comment by ashmilhussain** [comment]
I have seen a PR on this, 
PR: add FromCookie token extractor #10
Don't know why it's not merged.

**Comment by grounded042** [comment]
Sorry for the inactivity! Please see this comment for info: https://github.com/auth0/go-jwt-middleware/pull/10#issuecomment-770082747

**Comment by sergiughf** [comment]
We just released the [v2.0.0-beta](https://github.com/auth0/go-jwt-middleware/releases/tag/v2.0.0-beta) 🥳 ! 

You can start testing it by running `go get github.com/auth0/go-jwt-middleware/v2@v2.0.0-beta`. 

In case of issues fetching the v2 you might want to try `go clean --modcache` first before doing `go get`.

I'm closing this issue as now this is part of v2, but feel free to reopen if needed.
