### ISSUE TITLE
add option for additional checks

### ISSUE THREAD

**Issue by grounded042** [auth0/go-jwt-middleware#74]
At times consumers of the package want to validate more things in a token than what this package provides. The go to method of doing this is via the `ValidatonKeyGetter` func. We should provide specific functionality to do these checks instead of having users tack things into the key getter func.

**Comment by sergiughf** [comment]
We just released the [v2.0.0-beta](https://github.com/auth0/go-jwt-middleware/releases/tag/v2.0.0-beta) 🥳 ! 

You can start testing it by running `go get github.com/auth0/go-jwt-middleware/v2@v2.0.0-beta`. 

In case of issues fetching the v2 you might want to try `go clean --modcache` first before doing `go get`.

I'm closing this issue as now this is part of v2, but feel free to reopen if needed.
