### ISSUE TITLE
Generate token function

### ISSUE THREAD

**Issue by hmgle** [auth0/go-jwt-middleware#9]
I think to generate jwt token for login handler will make go-jwt-middleware easier to use. Do you have a plan to add this function like [go-json-rest-middleware-jwt](https://github.com/StephanDollberg/go-json-rest-middleware-jwt/blob/master/auth_jwt.go#L124)?

**Comment by grounded042** [comment]
There are no plans to add this at this time. Is this still something you would like to pursue? I'm going through and cleaning some things up, so if I don't hear back after a couple of days I'll close this issue.

**Comment by grounded042** [comment]
I'm closing this issue due to no response. If this is still a problem please feel free to re-open this issue.
