### ISSUE TITLE
jwt.Keyfunc

### ISSUE THREAD

**Issue by jiangjiali** [auth0/go-jwt-middleware#92]
无法将 'func(*jwt.Token) (interface{}, error) { return []byte(configure.Config.GetString("jwt.secret")), nil }' (类型 func(*jwt.Token) (interface{}, error)) 用作类型 jwt.Keyfunc

**Comment by DeamonMV** [comment]
@jiangjiali 
try this hack - change in your go.mod version of the go-jwt-middleware

from `github.com/auth0/go-jwt-middleware v1.0.0`
to `github.com/auth0/go-jwt-middleware v0.0.0-20190805220309-36081240882b`

**Comment by DeamonMV** [comment]
I'll elaborate little bit more about this problem.

I have spend whole day to understand why I cannot use my `func` in the ValidationKeyGetter. That is how it looks:
![image](https://user-images.githubusercontent.com/12302678/120900856-f88a8900-c63f-11eb-92df-438987cdc678.png)

At the end of the day I came up with idea to check version of the `go-jwt-middleware` module, and I have noticed that in the example repository https://github.com/auth0-blog/go-react-vr/blob/master/go.mod version is v0.0.0, and all works fine

But when I have create a go project from scratch, version was used v1.0.0, with which was a problem.

Can please someone help with this?
Thanks

**Comment by DeamonMV** [comment]
@jiangjiali if you please set this title for the issue

`Version v1.0.0 have issue on custom jwt.Keyfunc for ValidationKeyGetter`

I think this will expand more information about problem for other people. Thank you.

**Comment by jiangjiali** [comment]
Take the author to update the bug.
Thank you for taking the time to answer this less important question.

**Comment by grounded042** [comment]
The reason for this is when you upgrade to `v1.0.0` you need to use ` github.com/form3tech-oss/jwt-go` instead of `github.com/dgrijalva/jwt-go`. Context of this switch can be found here: https://github.com/auth0/go-jwt-middleware/pull/69#issuecomment-755391756

This project was not properly handling go module versioning which is why we had a breaking change like this. We will soon be releasing a v2 of the package which should handle things much better.

**Comment by grounded042** [comment]
@jiangjiali with the above comment is this still and issue you are hitting?

**Comment by jiangjiali** [comment]
Now there is no problem.
I fully understand.
